# Import module

In [79]:
!pip install -e .

^C

Obtaining file:///C:/Users/tranglt/Desktop/package_datacore
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: requests>=2.31.0 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from datacore==0.1.0) (2.33.1)
Requirement already satisfied: pandas>=2.0.0 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from datacore==0.1.0) (3.0.0)
Requirement already satisfied: python-dotenv>=1.0.0 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from datacore==0.1.0) (1.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=2.0.0->datacore==0.1.0) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=2.0.0->datacore==0.1.0) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=2.0.0->datacore==0.1.0) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.31.0->datacore==0.1.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.31.0->datacore==0.1.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.31.0->datacore==0.1.0) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.31.0->datacore==0.1.0) (2026.2.25)
Requirement already satisfied: six>=1.5 in c:\users\tranglt\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->datacore==0.1.0) (1.17.0)
Building wheels for collected packages: datacore
  Building editable for datacore (pyproject.toml): started
  Building editable for datacore (pyproject.toml): finished with status 'done'
  Created wheel for datacore: filename=datacore-0.1.0-0.editable-py3-none-any.whl size=4916 sha256=e2409565078a6a817f3e1c5608e2ea1fcc7168e675845369230b8ac9dc85b920
  Stored in directory: C:\Users\tranglt\AppData\Local\Temp\pip-ephem-wheel-cache-rbcad61h\wheels\f9\90\7c\0a30a204db3ace1fc036b5b3fd2a0ef9c18593258f8af7c0e7
Successfully built datacore
Installing collected packages: datacore
  Attempting uninstall: datacore
    Found existing installation: datacore 0.1.0
    Uninstalling datacore-0.1.0:
      Successfully uninstalled datacore-0.1.0
Successfully installed datacore-0.1.0

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: C:\Users\tranglt\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## 1. Initialize the client

In [ ]:
from datacore import Datacore

# Demo mode
client_demo = Datacore()

# Paid mode

x_api_key = "your_api_key" #Fill in your Datacore API key
client_paid = Datacore(api_key=x_api_key)

## 2. Preview a dataset (Demo mode)

In [81]:
# All columns
df_demo = client_demo.preview("dataset_historical_price")
df_demo

,symbol,date,high_price,low_price,open_price,average_price,close_price,basic_price,adj_ratio,unit,...,sel_val_foreign,buy_count,buy_vol,sell_count,sell_vol,foreign_room,prop_trading_deal,prop_trading_putth,prop_trading_net,year
0,CACB2404,2024-12-03,0.90,0.86,0.90,0.870100,0.89,0.90,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-107357000.0,0.0,-107357000.0,2024
1,CACB2404,2024-12-04,0.88,0.85,0.86,0.860699,0.88,0.89,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-72562000.0,0.0,-72562000.0,2024
2,CACB2404,2024-12-05,0.96,0.86,0.88,0.896716,0.96,0.88,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,65144000.0,0.0,65144000.0,2024
3,CACB2404,2024-12-06,0.97,0.94,0.95,0.947386,0.95,0.96,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-89753000.0,0.0,-89753000.0,2024
4,CACB2404,2024-12-09,0.96,0.90,0.92,0.901137,0.93,0.95,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-78117000.0,0.0,-78117000.0,2024
5,CACB2404,2024-12-10,0.93,0.90,0.92,0.907643,0.91,0.93,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-74885000.0,0.0,-74885000.0,2024
6,CACB2404,2024-12-11,0.93,0.88,0.92,0.904457,0.89,0.91,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-34076000.0,0.0,-34076000.0,2024
7,CACB2404,2024-12-12,0.92,0.89,0.91,0.901886,0.90,0.89,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-15088000.0,0.0,-15088000.0,2024
8,CACB2404,2024-12-13,0.90,0.84,0.90,0.859767,0.87,0.90,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,18446000.0,0.0,18446000.0,2024
9,CACB2404,2024-12-16,0.87,0.83,0.86,0.851494,0.85,0.87,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-171912000.0,0.0,-171912000.0,2024

In [82]:
print(df_demo.head(5))

     symbol        date  high_price  low_price  open_price  average_price  \
0  CACB2404  2024-12-03        0.90       0.86        0.90       0.870100
1  CACB2404  2024-12-04        0.88       0.85        0.86       0.860699
2  CACB2404  2024-12-05        0.96       0.86        0.88       0.896716
3  CACB2404  2024-12-06        0.97       0.94        0.95       0.947386
4  CACB2404  2024-12-09        0.96       0.90        0.92       0.901137

   close_price  basic_price  adj_ratio    unit  ...  sel_val_foreign  \
0         0.89         0.90        1.0  1000.0  ...              0.0
1         0.88         0.89        1.0  1000.0  ...              0.0
2         0.96         0.88        1.0  1000.0  ...              0.0
3         0.95         0.96        1.0  1000.0  ...              0.0
4         0.93         0.95        1.0  1000.0  ...              0.0

   buy_count  buy_vol  sell_count  sell_vol  foreign_room  prop_trading_deal  \
0        0.0      0.0         0.0       0.0    25000000.0       -107357000.0
1        0.0      0.0         0.0       0.0    25000000.0        -72562000.0
2        0.0      0.0         0.0       0.0    25000000.0         65144000.0
3        0.0      0.0         0.0       0.0    25000000.0        -89753000.0
4        0.0      0.0         0.0       0.0    25000000.0        -78117000.0

   prop_trading_putth  prop_trading_net  year
0                 0.0      -107357000.0  2024
1                 0.0       -72562000.0  2024
2                 0.0        65144000.0  2024
3                 0.0       -89753000.0  2024
4                 0.0       -78117000.0  2024

[5 rows x 28 columns]

In [83]:
# Filter specific columns
df_demo = client_demo.preview("dataset_historical_price", columns=["symbol", "date", "close_price"])
df_demo

     symbol        date  close_price
0  CACB2404  2024-12-03         0.89
1  CACB2404  2024-12-04         0.88
2  CACB2404  2024-12-05         0.96
3  CACB2404  2024-12-06         0.95
4  CACB2404  2024-12-09         0.93
5  CACB2404  2024-12-10         0.91
6  CACB2404  2024-12-11         0.89
7  CACB2404  2024-12-12         0.90
8  CACB2404  2024-12-13         0.87
9  CACB2404  2024-12-16         0.85

## 3. Fetch data (Paid mode)

In [ ]:
# All columns — returns {"data": DataFrame, "info": str}

result = client_paid.get_data("dataset_historical_price")
print(result["data"])
print(result["info"])

  symbol        date high_price low_price open_price average_price  \
0    AAA  2010-07-15       53.0      48.0       51.0       49.8864
1    AAA  2010-07-16       49.5      46.5       49.5       46.5607
2    AAA  2010-07-19       49.5      46.3       49.5        46.886
3    AAA  2010-07-20       48.0      44.5       48.0       45.2173
4    AAA  2010-07-21       45.4      44.0       45.2       45.1177
5    AAA  2010-07-22       48.0      45.0       45.1       45.6279
6    AAA  2010-07-23       47.5      45.8       47.5       46.5075
7    AAA  2010-07-26       46.8      45.0       46.1       46.0991
8    AAA  2010-07-27       47.0      45.4       46.5       46.1126
9    AAA  2010-07-28       46.9      45.0       46.9       45.7866

  close_price basic_price adj_ratio    unit  ... sel_val_foreign buy_count  \
0        48.7         0.0   4.58714  1000.0  ...             0.0     284.0
1        46.5        48.7   4.58714  1000.0  ...             0.0      95.0
2        46.3        46.5   4.58714  1000.0  ...             0.0     106.0
3        45.2        46.3   4.58714  1000.0  ...             0.0      86.0
4        45.1        45.2   4.58714  1000.0  ...             0.0      55.0
5        45.1        45.1   4.58714  1000.0  ...             0.0      91.0
6        46.0        45.1   4.58714  1000.0  ...             0.0      54.0
7        45.1        46.0   4.58714  1000.0  ...             0.0      55.0
8        46.1        45.1   4.58714  1000.0  ...             0.0      73.0
9        45.0        46.1   4.58714  1000.0  ...             0.0      56.0

    buy_vol sell_count  sell_vol foreign_room prop_trading_deal  \
0  850000.0       69.0  285800.0    3751000.0              None
1  109200.0       42.0  193900.0    3751000.0              None
2  203700.0       47.0  257800.0    3751000.0              None
3  637500.0       42.0  371000.0    3751000.0              None
4  106400.0       54.0  117600.0    3751000.0              None
5  167700.0       77.0  210300.0    3751000.0              None
6  165000.0       67.0  193500.0    3751000.0              None
7  164800.0       73.0  182700.0    3751000.0              None
8  159600.0       76.0  173000.0    3751000.0              None
9  230800.0       57.0  182300.0    3751000.0              None

  prop_trading_putth prop_trading_net  year
0               None             None  2010
1               None             None  2010
2               None             None  2010
3               None             None  2010
4               None             None  2010
5               None             None  2010
6               None             None  2010
7               None             None  2010
8               None             None  2010
9               None             None  2010

[10 rows x 28 columns]
num: 3760607, totalPage: 376061, currentPage: 1, queried_rows: 10

In [ ]:
# Filter specific columns
result = client_paid.get_data("dataset_historical_price", columns=["symbol", "date", "close_price"])
print(result["data"])
print(result["info"])

  symbol        date close_price
0    AAA  2010-07-15        48.7
1    AAA  2010-07-16        46.5
2    AAA  2010-07-19        46.3
3    AAA  2010-07-20        45.2
4    AAA  2010-07-21        45.1
5    AAA  2010-07-22        45.1
6    AAA  2010-07-23        46.0
7    AAA  2010-07-26        45.1
8    AAA  2010-07-27        46.1
9    AAA  2010-07-28        45.0
num: 3760607, totalPage: 376061, currentPage: 1, queried_rows: 10

## 4. Download data to file

In [ ]:
# Download all pages
download_result = client_paid.download_data(
    dataset_code="dataset_historical_price",
    output_path="dataset_historical_price_all.csv",  # hoặc .json
    file_format="csv",   # "csv" hoặc "json"
    start_page=1,
    end_page=None,       # để None là tải tới trang cuối
    show_progress=True,
)
print(download_result)

'download_result = client.download_data(\n    dataset_code="dataset_historical_price",\n    output_path="dataset_historical_price_all.csv",  # hoặc .json\n    file_format="csv",   # "csv" hoặc "json"\n    start_page=1,\n    end_page=None,       # để None là tải tới trang cuối\n    show_progress=True,\n)\nprint(download_result)'

In [ ]:
# Download only first 3 pages
download_result = client_paid.download_data(
    dataset_code="dataset_historical_price",
    output_path="dataset_historical_price_page1_3.json",
    file_format="json",  
    start_page=1,
    end_page=3,       
    show_progress=True,
)
print(download_result)

Downloading currentPage 3/376061...
{'output_path': 'dataset_historical_price_page1_3.json', 'file_format': 'json', 'pages_downloaded': 1, 'rows_downloaded': 10, 'start_page': 3, 'end_page': 3}

In [ ]:
# select columns to download
download_result = client_paid.download_data(
    dataset_code="dataset_historical_price",
    columns=["symbol", "date", "close_price"],
    output_path="dataset_historical_price_selected_cols.csv",
    file_format="csv",
    start_page=1,
    end_page=3,
    show_progress=True,
)
print(download_result)

Downloading currentPage 1/376061...
Downloading currentPage 2/376061...
Downloading currentPage 3/376061...
{'output_path': 'dataset_historical_price_selected_cols.csv', 'file_format': 'csv', 'pages_downloaded': 3, 'rows_downloaded': 30, 'start_page': 1, 'end_page': 3}

In [ ]:
# Download page 8 only
download_result = client_paid.download_data(
    dataset_code="dataset_historical_price",
    columns=["symbol", "date", "close_price"],
    output_path="dataset_historical_price_page8.csv",
    file_format="csv",
    start_page=8,
    end_page=8,
    show_progress=True,
)
print(download_result)

Downloading currentPage 8/376061...
{'output_path': 'dataset_historical_price_page8.csv', 'file_format': 'csv', 'pages_downloaded': 1, 'rows_downloaded': 10, 'start_page': 8, 'end_page': 8}