In [ ]:
!pip install -e .

In [1]:
from datacore import Datacore
client = Datacore()

In [2]:
df_demo = client.preview("dataset_historical_price", columns=["symbol", "date", "close_price"])
df_demo

     symbol        date  close_price
0  CACB2404  2024-12-03         0.89
1  CACB2404  2024-12-04         0.88
2  CACB2404  2024-12-05         0.96
3  CACB2404  2024-12-06         0.95
4  CACB2404  2024-12-09         0.93
5  CACB2404  2024-12-10         0.91
6  CACB2404  2024-12-11         0.89
7  CACB2404  2024-12-12         0.90
8  CACB2404  2024-12-13         0.87
9  CACB2404  2024-12-16         0.85

In [3]:
df_demo = client.preview("dataset_historical_price")
df_demo

,symbol,date,high_price,low_price,open_price,average_price,close_price,basic_price,adj_ratio,unit,...,sel_val_foreign,buy_count,buy_vol,sell_count,sell_vol,foreign_room,prop_trading_deal,prop_trading_putth,prop_trading_net,year
0,CACB2404,2024-12-03,0.90,0.86,0.90,0.870100,0.89,0.90,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-107357000.0,0.0,-107357000.0,2024
1,CACB2404,2024-12-04,0.88,0.85,0.86,0.860699,0.88,0.89,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-72562000.0,0.0,-72562000.0,2024
2,CACB2404,2024-12-05,0.96,0.86,0.88,0.896716,0.96,0.88,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,65144000.0,0.0,65144000.0,2024
3,CACB2404,2024-12-06,0.97,0.94,0.95,0.947386,0.95,0.96,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-89753000.0,0.0,-89753000.0,2024
4,CACB2404,2024-12-09,0.96,0.90,0.92,0.901137,0.93,0.95,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-78117000.0,0.0,-78117000.0,2024
5,CACB2404,2024-12-10,0.93,0.90,0.92,0.907643,0.91,0.93,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-74885000.0,0.0,-74885000.0,2024
6,CACB2404,2024-12-11,0.93,0.88,0.92,0.904457,0.89,0.91,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-34076000.0,0.0,-34076000.0,2024
7,CACB2404,2024-12-12,0.92,0.89,0.91,0.901886,0.90,0.89,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-15088000.0,0.0,-15088000.0,2024
8,CACB2404,2024-12-13,0.90,0.84,0.90,0.859767,0.87,0.90,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,18446000.0,0.0,18446000.0,2024
9,CACB2404,2024-12-16,0.87,0.83,0.86,0.851494,0.85,0.87,1.0,1000.0,...,0.0,0.0,0.0,0.0,0.0,25000000.0,-171912000.0,0.0,-171912000.0,2024

# Paid

In [5]:
# Call data
x_api_key = "REDACTED_LEAKED_API_KEY" #Fill in your Datacore API key
client = Datacore(api_key=x_api_key)

result = client.get_data("dataset_historical_price", columns=["symbol", "date", "close_price"])
print(result["data"].head())
print(result["info"])

  symbol        date close_price
0    AAA  2010-07-15        48.7
1    AAA  2010-07-16        46.5
2    AAA  2010-07-19        46.3
3    AAA  2010-07-20        45.2
4    AAA  2010-07-21        45.1
num: 3760607, totalPage: 376061, currentPage: 1, queried_rows: 10

In [6]:

result = client.get_data("gross_domestic_product_dataset_ds")
print(result["data"].head())
print(result["info"])

                            country country_iso  year gdp_const_lcu  \
0  Afghanistan, Islamic Republic of         AFG  2002       453.484
1  Afghanistan, Islamic Republic of         AFG  2003       492.903
2  Afghanistan, Islamic Republic of         AFG  2004       496.209
3  Afghanistan, Islamic Republic of         AFG  2005        554.91
4  Afghanistan, Islamic Republic of         AFG  2006       584.658

  gdp_const_pc_lcu gdp_const_pc_ppp gdp_const_growth gdp_current_lcu  \
0         21594.23         1681.504              NaN         178.756
1        21766.381         1694.909            8.692         220.013
2        21067.277         1640.471            0.671          246.21
3        22731.779         1770.083            11.83         304.926
4        22979.189         1789.348            5.361         345.817

  gdp_current_usd
0           4.367
1           4.553
2           5.146
3           6.167
4           6.925
num: 7551, totalPage: 756, currentPage: 1, queried_rows: 10

In [7]:

result = client.get_data("dataset_historical_price")
print(result["data"].head())
print(result["info"])

  symbol        date high_price low_price open_price average_price  \
0    AAA  2010-07-15       53.0      48.0       51.0       49.8864
1    AAA  2010-07-16       49.5      46.5       49.5       46.5607
2    AAA  2010-07-19       49.5      46.3       49.5        46.886
3    AAA  2010-07-20       48.0      44.5       48.0       45.2173
4    AAA  2010-07-21       45.4      44.0       45.2       45.1177

  close_price basic_price adj_ratio    unit  ... sel_val_foreign buy_count  \
0        48.7         0.0   4.58714  1000.0  ...             0.0     284.0
1        46.5        48.7   4.58714  1000.0  ...             0.0      95.0
2        46.3        46.5   4.58714  1000.0  ...             0.0     106.0
3        45.2        46.3   4.58714  1000.0  ...             0.0      86.0
4        45.1        45.2   4.58714  1000.0  ...             0.0      55.0

    buy_vol sell_count  sell_vol foreign_room prop_trading_deal  \
0  850000.0       69.0  285800.0    3751000.0              None
1  109200.0       42.0  193900.0    3751000.0              None
2  203700.0       47.0  257800.0    3751000.0              None
3  637500.0       42.0  371000.0    3751000.0              None
4  106400.0       54.0  117600.0    3751000.0              None

  prop_trading_putth prop_trading_net  year
0               None             None  2010
1               None             None  2010
2               None             None  2010
3               None             None  2010
4               None             None  2010

[5 rows x 28 columns]
num: 3760607, totalPage: 376061, currentPage: 1, queried_rows: 10

In [ ]:
#download lần lượt các page
'''download_result = client.download_data(
    dataset_code="dataset_historical_price",
    output_path="dataset_historical_price_all.csv",  # hoặc .json
    file_format="csv",   # "csv" hoặc "json"
    start_page=1,
    end_page=None,       # để None là tải tới trang cuối
    show_progress=True,
)
print(download_result)'''

'download_result = client.download_data(\n    dataset_code="dataset_historical_price",\n    output_path="dataset_historical_price_all.csv",  # hoặc .json\n    file_format="csv",   # "csv" hoặc "json"\n    start_page=1,\n    end_page=None,       # để None là tải tới trang cuối\n    limit=1000,\n    show_progress=True,\n)\nprint(download_result)'

In [8]:
#download lần lượt các page được chọn
download_result = client.download_data(
    dataset_code="dataset_historical_price",
    output_path="dataset_historical_price_page1_3.json",  # hoặc .json
    file_format="json",   # "csv" hoặc "json"
    start_page=1,
    end_page=1,       # để None là tải tới trang cuối
    show_progress=True,
)
print(download_result)

APIRequestError: Invalid request content.

In [11]:
# select columns to download
download_result = client.download_data(
    dataset_code="dataset_historical_price",
    columns=["symbol", "date", "close_price"],
    output_path="dataset_historical_price_selected_cols.csv",
    file_format="csv",
    start_page=1,
    end_page=3,
    show_progress=True,
)
print(download_result)
##

Downloading currentPage 1/37607...
Downloading currentPage 2/37607...
Downloading currentPage 3/37607...
{'output_path': 'dataset_historical_price_selected_cols.csv', 'file_format': 'csv', 'pages_downloaded': 3, 'rows_downloaded': 300, 'start_page': 1, 'end_page': 3}